### ISSUE TITLE
Individuelle Einstellungen speichern und importieren

### ISSUE THREAD

**Issue by Schmidty2** [madeyourday/contao-rocksolid-theme-assistant#4]
Hallo,
kann die Funktion hinzugefügt werden, dass eigene, induviduelle Einstellungen des Theme-Designers gespeichert und wieder importiert werden können.
Danke.

**Comment by ausi** [comment]
Für individuelle Anpassungen ist die *custom.css*-Datei des jeweiligen Themes gedacht. Eigene Einstellungen sind im Theme Assistant nicht vorgesehen.

**Comment by Schmidty2** [comment]
Hallo,

dass individuelle Anpassungen in der custom.css eingetragen werden, ist mir bekannt.
Warum aber dann der Theme-Designer, in dem ich Farben und Abstände definieren kann?

Zur Erklärung:

Wenn ich mit dem Theme-Designer Anpassungen vornehme, werden diese direkt in der main.css gespeichert. Steht jetzt ein Theme-Update an und man muss die main.css wegen des Theme-Updates überschreiben (oder man überschreibt dabei versehentlich die Datei main.css), sind alle individuellen Einstellungen des Theme-Designers weg und müssen mühsam wieder durch Änderungen der einzelnen Einträge im Theme-Designer hergestellt werden.
Aber auch wenn man mit verschiedenen eigenen Themevariationen arbeiten möchte um z.B. die geeignete Farbkombination bzw. die optimalen Einstellungen zu finden, müssen die Angaben der Farben, Abstände usw. jedes Mal einzeln im Theme-Designer eingetragen werden.
Wenn der Theme-Designer eine Im- und Export-Funktion hätte, könnten diese Einstellungen gespeichert und wiederhergestellt werden. Eventuell könnte der Theme-Designer seine Einstellungen auch direkt in die custom.css schreiben, dann bleiben die Einstellungen ja ebenfalls erhalten.

**Comment by ausi** [comment]
Die Einstellungen sind in der Datei *main.css.base* gespeichert. Wenn Sie diese Datei nicht ersetzen, bleiben die Einstellungen erhalten.
