### ISSUE TITLE
Erweiterung für SASS-Datein

### ISSUE THREAD

**Issue by arboc** [madeyourday/contao-rocksolid-theme-assistant#5]
Der Assistent prpft auf html(5)- und css-Dateien....

Kann das nicht auch auf scss-Dateien erweitert werden, die im Prinzip wie css-Dateien geparsed werden könnten?
Soweit ich das sehe, müssten nur im onload- und onsubmit-callback eine Zeile bei der ybestimmumg des type angepasst werden:

alt:  
`if (substr($dc->id, -9, 4) === '.css') {`

neu:
`if (substr($dc->id, -9, 4) === '.css' || substr($dc->id, -10, 5) === '.scss') {`

**Comment by ausi** [comment]
Der Theme Assistant kann für die SCSS-Dateien des Themes nicht verwendet werden.

Bei Verwendung der SCSS-Dateien, können die Einstellungen des Theme Assistant direkt in den Sass-Variablen vorgenommen werden.
