### ISSUE TITLE
templates/eightytwenty/fe_page.html5.base deprecated in 1.8.7?

### ISSUE THREAD

**Issue by Aybee** [madeyourday/contao-rocksolid-theme-assistant#6]
Hallo Martin, ich bin hier gerade in nem BE gelandet wo so eine Datei im Template-Ordner liegt.
`templates/eightytwenty/fe_page.html5.base`

Die ist bei dem neuen Theme 80/20 1.8.7 für Contao 4.4/7 nicht dabei. Kann ich diese Datei einfach löschen?

ps Hatte ein paar Probleme bis ich im BE die main.css.base beim Assistant überhaupt angezeigt bekam. Nach einer Synchronisierung der Dateien ging es dann aber.

**Comment by ausi** [comment]
> Kann ich diese Datei einfach löschen?

Ja, diese Datei wird in neueren Theme-Versionen nicht mehr verwendet.

Weitere Fragen zu den Themes kannst du jederzeit über <https://my.rocksolidthemes.com/support> stellen.

**Comment by Aybee** [comment]
OK, vielen Dank. Habe schon gesehen, dass der Kunde jetzt etwas anders vorgehen muss, z.B. um sein Logo rein zu bekommen.
